FROM python:3.10

RUN mkdir /app
WORKDIR /app
COPY requirements_cpu.txt requirements.txt
RUN pip install -r requirements.txt

COPY . .

CMD ["uvicorn", "api.api:app", "--host", "0.0.0.0", "--port", "9971"]
